{{- if .Values.rbac.create }}
apiVersion: v1
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "conntrack-exporter.fullname" . }}
  labels:
    app: {{ template "conntrack-exporter.name" . }}
{{ include "conntrack-exporter.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - pods
  verbs:
  - get
  - list
{{ end }}
