{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "conntrack-exporter.fullname" . }}
  namespace: {{ template "conntrack-exporter.namespace" . }}
  labels:
{{ include "conntrack-exporter.labels" . | indent 4 }}
{{- if .Values.podMonitor.additionalLabels }}
{{ toYaml .Values.podMonitor.additionalLabels | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "conntrack-exporter.name" . }}
  podMetricsEndpoints:
    - port: http-metrics
      scheme: {{ $.Values.podMonitor.scheme }}
      {{- if $.Values.podMonitor.bearerTokenFile }}
      bearerTokenFile: {{ $.Values.podMonitor.bearerTokenFile }}
      {{- end }}
      {{- if $.Values.podMonitor.tlsConfig }}
      tlsConfig: {{ toYaml $.Values.podMonitor.tlsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
      {{- end }}
{{- if .Values.podMonitor.relabelings }}
      relabelings:
{{ toYaml .Values.podMonitor.relabelings | indent 8 }}
{{- end }}
{{- end }}
