{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "conntrack-exporter.serviceAccountName" . }}
  labels:
{{ include "conntrack-exporter.labels" . | indent 4 }}
{{- end -}}
