"""Added Invoice table

Revision ID: 008
Revises: 007
Create Date: 2023-01-31 23:37:46.425715

"""
from alembic import op
import sqlalchemy as sa
import infrastructure.postgres.tables.base


# revision identifiers, used by Alembic.
revision = '008'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sub_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', infrastructure.postgres.tables.base.TimeStamp(), nullable=True),
    sa.Column('deleted_at', infrastructure.postgres.tables.base.TimeStamp(), nullable=True),
    sa.Column('due', infrastructure.postgres.tables.base.TimeStamp(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('account_address', sa.String(), nullable=True),
    sa.Column('account_email', sa.String(), nullable=True),
    sa.Column('period_start', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
