"""Added Account

Revision ID: 001
Revises: 
Create Date: 2023-01-29 09:50:05.708176

"""
import sqlalchemy as sa
from alembic import op

from infrastructure.postgres.tables.base import TimeStamp

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('created_at', TimeStamp(), nullable=True),
                    sa.Column('deleted_at', TimeStamp(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('phone', sa.String(length=255), nullable=True),
                    sa.Column('version_number', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_table('account_balances',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('created_at', TimeStamp(), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=True),
                    sa.Column('account_id', sa.String(length=32), nullable=True),
                    sa.Column('version_number', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_account_balances_account_id'), 'account_balances', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_balances_created_at'), 'account_balances', ['created_at'], unique=False)
    op.create_table('transactions',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('created_at', TimeStamp(), nullable=True),
                    sa.Column('balance_id', sa.String(length=32), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=True),
                    sa.Column('transaction_type', sa.String(length=32), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['balance_id'], ['account_balances.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_transactions_balance_id'), 'transactions', ['balance_id'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_balance_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_account_balances_created_at'), table_name='account_balances')
    op.drop_index(op.f('ix_account_balances_account_id'), table_name='account_balances')
    op.drop_table('account_balances')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
