"""Added Subscription Items

Revision ID: 005
Revises: 004
Create Date: 2023-01-31 16:13:29.024481

"""
import infrastructure.postgres.tables.base
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_items',
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', infrastructure.postgres.tables.base.TimeStamp(), nullable=True),
    sa.Column('deleted_at', infrastructure.postgres.tables.base.TimeStamp(), nullable=True),
    sa.Column('sub_id', sa.String(length=32), nullable=True),
    sa.Column('price_id', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_subscription_items_created_at'), 'subscription_items', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_items_created_at'), table_name='subscription_items')
    op.drop_table('subscription_items')
    # ### end Alembic commands ###
