"""Update Subscription Item field

Revision ID: 007
Revises: 006
Create Date: 2023-01-31 20:20:46.580449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_items', sa.Column('id', sa.String(length=32), nullable=False))
    op.drop_column('subscription_items', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_items', sa.Column('item_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('subscription_items', 'id')
    # ### end Alembic commands ###
