"""Added Price

Revision ID: 003
Revises: 002
Create Date: 2023-01-30 10:59:03.423868

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import infrastructure.postgres.tables.base

# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('product_id', sa.String(length=32), nullable=False),
                    sa.Column('created_at', infrastructure.postgres.tables.base.TimeStamp(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('lookup_key', sa.String(), nullable=True),
                    sa.Column('tiers_mode', sa.String(), nullable=True),
                    sa.Column('recurring', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    # ### end Alembic commands ###
