"""Added Product

Revision ID: 002
Revises: 001
Create Date: 2023-01-29 22:45:05.984947

"""
import sqlalchemy as sa
from alembic import op

import infrastructure.postgres.tables.base

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('created_at', infrastructure.postgres.tables.base.TimeStamp(), nullable=True),
                    sa.Column('deleted_at', infrastructure.postgres.tables.base.TimeStamp(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('unit_label', sa.String(length=255), nullable=True),
                    sa.Column('version_number', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
