"""Added Subscription

Revision ID: 004
Revises: 003
Create Date: 2023-01-31 16:10:15.623849

"""
import infrastructure.postgres.tables.base
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "004"
down_revision = "003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at", infrastructure.postgres.tables.base.TimeStamp(), nullable=True
        ),
        sa.Column(
            "deleted_at", infrastructure.postgres.tables.base.TimeStamp(), nullable=True
        ),
        sa.Column("account_id", sa.String(length=32), nullable=True),
        sa.Column("current_period_start", sa.Integer(), nullable=True),
        sa.Column("current_period_end", sa.Integer(), nullable=True),
        sa.Column("cancel_at", sa.Integer(), nullable=True),
        sa.Column("cancelled", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_created_at"), "subscription", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_created_at"), table_name="subscription")
    op.drop_table("subscription")
    # ### end Alembic commands ###
