apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rpaas-api.fullname" . }}-conf
  labels:
    {{- include "rpaas-api.labels" . | nindent 4 }}
data:
  rpaas-api-conf.yaml: |-
{{ .Values.config | toYaml | indent 4 }}
