# Default values for ip-masq-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: k8s.gcr.io/networking/ip-masq-agent-amd64
  pullPolicy: IfNotPresent
  tag: "v2.6.0"

args: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

securityContext:
  privileged: true

resources: {}

nodeSelector: {}

tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - key: "CriticalAddonsOnly"
    operator: "Exists"

affinity: {}

ipMasqConfig: {}

lifecycle: {}
