{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tsuru-api.fullname" . }}
  labels:
    {{- include "tsuru-api.labels" . | nindent 4 }}
spec:
  endpoints:
  {{- if .Values.service.httpsOnly }}
  - honorLabels: true
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  {{- else }}
  - honorLabels: true
    port: http
  {{- end }}
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      {{- include "tsuru-api.selectorLabels" . | nindent 6 }}
{{- end }}
