{{- if .Values.calicoNode.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: calico-node
  labels:
{{ include "tsuru-monitoring.labels" . | indent 4 }}
{{- with .Values.calicoNode.podMonitorLabels }}
{{ toYaml . | indent 4 }}
{{- end }}

spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: calico-node
{{- end }}
