apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
{{ include "tsuru-monitoring.labels" . | indent 4 }}
{{- if .Values.tsuruRules.labels }}
{{ toYaml .Values.tsuruRules.labels | indent 4 }}
{{- end }}
{{- if .Values.tsuruRules.annotations }}
  annotations:
{{ toYaml .Values.tsuruRules.annotations | indent 4 }}
{{- end }}
  name: tsuru-apps-rule
spec:
  groups:
  - interval: 30s
    name: tsuru-apps.rules
    rules:
    - record: tsuru:apps_cpu_usage_seconds_total
      expr: |
        container_cpu_usage_seconds_total{container!="POD", container!="", pod!=""} *
        on (pod) group_left(label_tsuru_io_app_name, label_version, label_tsuru_io_app_process, label_tsuru_io_app_pool) kube_pod_labels{label_tsuru_io_is_tsuru="true"}
    - record: tsuru:apps_memory_working_set_bytes
      expr: |
        container_memory_working_set_bytes{container!="POD", container!="", pod!=""} *
        on (pod) group_left(label_tsuru_io_app_name, label_version, label_tsuru_io_app_process, label_tsuru_io_app_pool) kube_pod_labels{label_tsuru_io_is_tsuru="true"}
