{{ if .Values.ipMasqConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ip-masq-agent.fullname" . }}
  labels:
    {{- include "ip-masq-agent.labels" . | nindent 4 }}
data:
  config: |-
    {{- toYaml .Values.ipMasqConfig | nindent 4}}
{{ end }}