apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "..fullname" . }}-reader
  labels:
    {{- include "..labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ include "..fullname" . }}-reader
subjects:
- kind: ServiceAccount
  name: {{ include "..serviceAccountName" . }}
