{{- $poolName := .Values.tsuru.pool.name -}}
{{- $count := .Values.replicaCount | int -}}
{{- $labels := include "..labels" . -}}
{{- $ingressPerReplica := .Values.ingressPerReplica -}}
{{- $fullName := include "..fullname" . -}}
{{- $baseHost := .Values.ingress.host -}}
{{- $baseAnnotations := .Values.ingress.annotations -}}

apiVersion: v1
kind: List
metadata:
  name: prometheus-serviceperreplica
items:
{{- range $i, $e := until $count }}
- apiVersion: v1
  kind: Service
  metadata:
    name: prometheus-{{ $fullName }}-{{$i}}
    labels:
      {{- $labels | nindent 6}}
  spec:
    ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      prometheus: tsuru-prometheus-pool
      tsuru.io/pool: {{ $poolName }}
      statefulset.kubernetes.io/pod-name: prometheus-{{ $fullName }}-{{$i}}
    type: ClusterIP
{{- if $ingressPerReplica.enabled }}
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: prometheus-{{ $fullName }}-{{$i}}
    labels:
      {{- $labels | nindent 6}}
    {{- with $baseAnnotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  spec:
    rules:
    - host: replica{{$i}}.{{ $baseHost }}
      http:
        paths:
        - backend:
            service:
              name: prometheus-{{ $fullName }}-{{$i}}
              port:
                number: 9090
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - replica{{$i}}.{{ $baseHost }}
      secretName: tsuru-prometheus-pool-replica-{{$i}}
{{- end }}
{{- end -}}
