apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    tsuru.io/pool: {{ .Values.tsuru.pool.name }}
    prometheus: tsuru-prometheus-pool