{{- if .Values.rpaas.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    tsuru.io/pool: {{ .Values.tsuru.pool.name }}
    {{- include "..labels" . | nindent 4 }}
  name: tsuru-rpaas-rule
spec:
  groups:
  - interval: 30s
    name: tsuru-rpaas.rules
    rules:
      - expr: |
          container_memory_working_set_bytes{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_memory_working_set_bytes"

      - expr: |
          container_cpu_usage_seconds_total{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_cpu_usage_seconds_total"

      - expr: |
          container_network_receive_bytes_total{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_network_receive_bytes_total"

      - expr: |
          container_network_transmit_bytes_total{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_network_transmit_bytes_total"

      - expr: |
          container_cpu_load_average_10s{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_cpu_load_average_10s"

      - expr: |
          container_spec_memory_limit_bytes{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_spec_memory_limit_bytes"

      - expr: |
          sum by (namespace, service_instance, service, le) (increase(nginx_vts_server_request_duration_seconds_bucket{service_instance!=""}[2m]))/2
        record: "rpaas:nginx_vts_server_request_duration_seconds_bucket:increase_1m"
{{- end }}
