"""fixed tables

Revision ID: 007
Revises: 006
Create Date: 2023-02-01 10:11:58.529481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('source_url', sa.Text(), nullable=False))
    op.add_column('deployments', sa.Column('source_type', sa.Text(), nullable=False))
    op.add_column('deployments', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('deployments', sa.Column('image_registry', sa.Text(), nullable=True))
    op.add_column('deployments', sa.Column('image_tag', sa.String(length=255), nullable=True))
    op.drop_column('deployments', 'deployment_type')
    op.drop_column('deployments', 'deployment_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('deployment_source', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('deployments', sa.Column('deployment_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('deployments', 'image_tag')
    op.drop_column('deployments', 'image_registry')
    op.drop_column('deployments', 'image_url')
    op.drop_column('deployments', 'source_type')
    op.drop_column('deployments', 'source_url')
    # ### end Alembic commands ###
