"""fixed tables

Revision ID: 009
Revises: 008
Create Date: 2023-02-02 02:45:07.981353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009'
down_revision = '008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('platform', sa.String(length=32), nullable=True))
    op.add_column('apps', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'description')
    op.drop_column('apps', 'platform')
    # ### end Alembic commands ###
