"""Added members table

Revision ID: 003
Revises: 002
Create Date: 2023-01-31 17:54:47.512255

"""
import sqlalchemy as sa
from alembic import op

import src.infrastructure.postgres.models.base

# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('project_id', sa.String(length=32), nullable=True),
                    sa.Column('user_id', sa.String(length=32), nullable=True),
                    sa.Column('created_at', src.infrastructure.postgres.models.base.TimeStamp(), nullable=True),
                    sa.Column('role', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_project_members_created_at'), 'project_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_created_at'), table_name='project_members')
    op.drop_table('project_members')
    # ### end Alembic commands ###
