"""resize id

Revision ID: bd3b52429399
Revises: 009
Create Date: 2023-02-09 01:10:16.664687

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd3b52429399'
down_revision = '009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('activities', 'app_id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('apps', 'id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('apps', 'project_id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('apps', 'status',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('apps', 'platform',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('deployments', 'id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('deployments', 'app_id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('deployments', 'scale_id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('environments', 'id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('environments', 'app_id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('project_members', 'id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('project_members', 'project_id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('project_members', 'user_id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('projects', 'id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('scales', 'id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('scales', 'app_id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('scales', 'unit_id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('units', 'id',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('users', 'id',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False)
    op.alter_column('units', 'id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False)
    op.alter_column('scales', 'unit_id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('scales', 'app_id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('scales', 'id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False)
    op.alter_column('projects', 'id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False)
    op.alter_column('project_members', 'user_id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('project_members', 'project_id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('project_members', 'id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False)
    op.alter_column('environments', 'app_id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('environments', 'id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False)
    op.alter_column('deployments', 'scale_id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('deployments', 'app_id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('deployments', 'id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False)
    op.alter_column('apps', 'platform',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('apps', 'status',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('apps', 'project_id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('apps', 'id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False)
    op.alter_column('activities', 'app_id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('activities', 'id',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=False)
    # ### end Alembic commands ###
