"""empty message

Revision ID: 001. Init
Revises: 
Create Date: 2023-01-01 22:18:59.601662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001. Init'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_created_at'), 'plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_plans_deleted_at'), 'plans', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('apps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('plan_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apps_created_at'), 'apps', ['created_at'], unique=False)
    op.create_index(op.f('ix_apps_deleted_at'), 'apps', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_apps_id'), 'apps', ['id'], unique=False)
    op.create_index(op.f('ix_apps_name'), 'apps', ['name'], unique=True)
    op.create_index(op.f('ix_apps_plan_id'), 'apps', ['plan_id'], unique=False)
    op.create_index(op.f('ix_apps_project_id'), 'apps', ['project_id'], unique=False)
    op.create_table('balance_adjustments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_adjustments_created_at'), 'balance_adjustments', ['created_at'], unique=False)
    op.create_index(op.f('ix_balance_adjustments_deleted_at'), 'balance_adjustments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_balance_adjustments_id'), 'balance_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_balance_adjustments_project_id'), 'balance_adjustments', ['project_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('plan_id', sa.String(length=32), nullable=True),
    sa.Column('billing_cycle', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('cycle_started_at', sa.DateTime(), nullable=True),
    sa.Column('cycle_ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_billing_cycle'), 'subscriptions', ['billing_cycle'], unique=False)
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_cycle_ends_at'), 'subscriptions', ['cycle_ends_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_cycle_started_at'), 'subscriptions', ['cycle_started_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_deleted_at'), 'subscriptions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_project_id'), 'subscriptions', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_project_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_deleted_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_cycle_started_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_cycle_ends_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_billing_cycle'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_balance_adjustments_project_id'), table_name='balance_adjustments')
    op.drop_index(op.f('ix_balance_adjustments_id'), table_name='balance_adjustments')
    op.drop_index(op.f('ix_balance_adjustments_deleted_at'), table_name='balance_adjustments')
    op.drop_index(op.f('ix_balance_adjustments_created_at'), table_name='balance_adjustments')
    op.drop_table('balance_adjustments')
    op.drop_index(op.f('ix_apps_project_id'), table_name='apps')
    op.drop_index(op.f('ix_apps_plan_id'), table_name='apps')
    op.drop_index(op.f('ix_apps_name'), table_name='apps')
    op.drop_index(op.f('ix_apps_id'), table_name='apps')
    op.drop_index(op.f('ix_apps_deleted_at'), table_name='apps')
    op.drop_index(op.f('ix_apps_created_at'), table_name='apps')
    op.drop_table('apps')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_deleted_at'), table_name='plans')
    op.drop_index(op.f('ix_plans_created_at'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
