"""fixed tables

Revision ID: 006
Revises: 005
Create Date: 2023-02-01 07:41:29.833817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plans_created_at', table_name='plans')
    op.drop_index('ix_plans_deleted_at', table_name='plans')
    op.drop_index('ix_plans_lookup_key', table_name='plans')
    op.drop_index('ix_plans_price_id', table_name='plans')
    op.drop_table('plans')
    op.drop_column('deployments', 'version_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('plans',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('lookup_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('price_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='plans_pkey')
    )
    op.create_index('ix_plans_price_id', 'plans', ['price_id'], unique=False)
    op.create_index('ix_plans_lookup_key', 'plans', ['lookup_key'], unique=False)
    op.create_index('ix_plans_deleted_at', 'plans', ['deleted_at'], unique=False)
    op.create_index('ix_plans_created_at', 'plans', ['created_at'], unique=False)
    # ### end Alembic commands ###
