{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rpaas-purger
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rpaas-purger
subjects:
- kind: ServiceAccount
  name: {{ include "rpaas-purger.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: rpaas-purger
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rpaas-purger.serviceAccountName" . }}
  labels:
    {{- include "rpaas-purger.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
