apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "certmanager-certificate.labels" . | nindent 4 }}
spec:
{{ toYaml .Values.spec | indent 2 }}