kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "rpaas-operator.fullname" . }}:manager"
  labels:
    {{- include "rpaas-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "rpaas-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.additionalSubjectsAllowed }}
{{ toYaml . }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "rpaas-operator.fullname" . }}:manager"
