{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acl-operator.serviceAccountName" . }}
  labels:
    {{- include "acl-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acl-operator.fullname" . }}
  labels:
    {{- include "acl-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "extensions.tsuru.io"
      - "tsuru.io"
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - "*"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "acl-operator.fullname" . }}
  labels:
    {{- include "acl-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "acl-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "acl-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
