apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "certmanager-cluster-issuer.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.annotations | nindent 4 }}
spec:
{{ toYaml .Values.spec | indent 2 }}