apiVersion: v1
kind: Secret
metadata:
  name: {{ include "networkapi-ingress-controller.fullname" . }}
  labels:
    {{- include "networkapi-ingress-controller.labels" . | nindent 4 }}
data:
  username: {{ .Values.networkapi.username | b64enc | quote }}
  password: {{ .Values.networkapi.password | b64enc | quote }}