kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "nginx-operator.fullname" . }}:manager"
  labels:
    {{- include "nginx-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "nginx-operator.fullname" . }}:manager"
subjects:
- kind: ServiceAccount
  name: {{ include "nginx-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
