apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "nginx-operator.fullname" . }}:leader-election"
  labels:
    {{- include "nginx-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "nginx-operator.fullname" . }}:leader-election"
subjects:
- kind: ServiceAccount
  name: {{ include "nginx-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
